<?php
declare(strict_types=1);

namespace QSYN\Admin;

/**
 * One-time website password creation requires proof of private-file ownership.
 *
 * A high-entropy pairing code is GENERATED by PHP on the first pre-login
 * status request but is NEVER returned over HTTP. The site owner retrieves
 * it via authenticated, private Cloudways SFTP/file management.
 *
 * No existing invalid administrator file can be overwritten or recovered
 * by this mechanism. Explicit QSYN_CONTROL_ENABLED=0 disables setup.
 */
final class RustAdminBootstrap
{
    private const CODE_FILE = 'admin-setup-code.txt';
    private const AUTH_FILE = 'admin-auth.json';

    private static function directory(): ?string
    {
        $dir = (string)(getenv('QSYN_RUNTIME_DIR') ?: dirname(__DIR__, 2) . '/runtime');
        if (!str_starts_with($dir, '/') ||
            preg_match('~(?:^|/)\.\.(?:/|$)~', $dir) ||
            !is_dir($dir) || is_link($dir) || !is_writable($dir)) {
            return null;
        }
        $perms = @fileperms($dir);
        return $perms !== false && ($perms & 0002) === 0 ? rtrim($dir, '/') : null;
    }

    private static function eligible(string $directory): bool
    {
        if (getenv('QSYN_CONTROL_ENABLED') === '0' ||
            RustAdmin::configured() ||
            (string)getenv('QSYN_ADMIN_PASSWORD_HASH') !== '') {
            return false;
        }
        $target = $directory . '/' . self::AUTH_FILE;
        // Corrupt, disabled, or symlinked existing config is NOT a fresh install.
        return !file_exists($target) && !is_link($target);
    }

    /** Private lock with an exclusive owner-only setup-token lifecycle. */
    private static function withLock(string $directory, callable $callback): mixed
    {
        $file = $directory . '/.admin-setup.lock';
        if (is_link($file)) return null;
        $handle = @fopen($file, 'c');
        if ($handle === false) return null;
        try {
            @chmod($file, 0600);
            $mode = @fileperms($file);
            if ($mode === false || ($mode & 0077) !== 0 || !@flock($handle, LOCK_EX)) {
                return null;
            }
            try {
                return $callback();
            } finally {
                flock($handle, LOCK_UN);
            }
        } finally {
            fclose($handle);
        }
    }

    private static function verifiedCode(string $path): ?string
    {
        clearstatcache(true, $path);
        if (is_link($path) || !is_file($path) || !is_readable($path)) return null;
        $mode = @fileperms($path);
        $size = @filesize($path);
        if ($mode === false || ($mode & 0077) !== 0 || $size !== 65) return null;
        $code = @file_get_contents($path);
        return is_string($code) && preg_match('/^[a-f0-9]{64}\n$/D', $code) === 1
            ? substr($code, 0, 64) : null;
    }

    public static function status(): array
    {
        $directory = self::directory();
        if ($directory === null || !self::eligible($directory)) {
            return ['available' => false, 'reason' => 'setup_not_available'];
        }
        $ready = self::withLock($directory, static function () use ($directory): bool {
            if (!self::eligible($directory)) return false;
            $path = $directory . '/' . self::CODE_FILE;
            if (is_link($path)) return false;
            if (file_exists($path)) return self::verifiedCode($path) !== null;
            // Creating the private setup code is safe on unauthenticated GET:
            // it grants NO privilege and never returns the code over HTTP.
            $handle = @fopen($path, 'x');
            if ($handle === false) return false;
            try {
                $code = bin2hex(random_bytes(32)) . "\n";
                $ok = @fwrite($handle, $code) === strlen($code)
                    && @fflush($handle) && @chmod($path, 0600);
            } finally {
                fclose($handle);
            }
            if (!$ok) {
                @unlink($path);
                return false;
            }
            return self::verifiedCode($path) !== null;
        });
        return [
            'available' => $ready === true,
            'reason' => $ready === true ? 'private_code_ready' : 'setup_not_available',
        ];
    }

    public static function complete(string $code, string $password): array
    {
        if (strlen($code) !== 64 || preg_match('/^[a-f0-9]{64}$/D', $code) !== 1 ||
            strlen($password) < 20 || strlen($password) > 1024) {
            return ['ok' => false, 'error' => 'invalid_setup_credentials'];
        }
        if ((int)($_SESSION['qsyn_setup_lock_until'] ?? 0) > time()) {
            return ['ok' => false, 'error' => 'setup_rate_limited'];
        }
        $directory = self::directory();
        if ($directory === null || !self::eligible($directory)) {
            return ['ok' => false, 'error' => 'setup_unavailable'];
        }
        $result = self::withLock($directory, static function () use ($directory, $code, $password): bool {
            if (!self::eligible($directory)) return false;
            $setupFile = $directory . '/' . self::CODE_FILE;
            $expected = self::verifiedCode($setupFile);
            if ($expected === null || !hash_equals($expected, $code)) return false;

            $hash = password_hash($password, PASSWORD_DEFAULT);
            if (!is_string($hash)) return false;
            $data = json_encode([
                'schema' => 'QSYN-ADMIN/1',
                'enabled' => true,
                'password_hash' => $hash,
            ], JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES) . "\n";
            $temp = $directory . '/.admin-auth-' . bin2hex(random_bytes(8));
            $handle = @fopen($temp, 'x');
            if ($handle === false) return false;
            try {
                $written = @fwrite($handle, $data) === strlen($data) &&
                    @fflush($handle) && @chmod($temp, 0600);
            } finally {
                fclose($handle);
            }
            if (!$written) {
                @unlink($temp);
                return false;
            }
            // Atomic no-overwrite publish. A concurrent SFTP-created admin
            // configuration must NEVER be silently replaced.
            $published = @link($temp, $directory . '/' . self::AUTH_FILE);
            @unlink($temp);
            if (!$published) return false;
            @unlink($setupFile);
            return true;
        });
        if ($result !== true) {
            $fails = (int)($_SESSION['qsyn_setup_failures'] ?? 0) + 1;
            $_SESSION['qsyn_setup_failures'] = $fails;
            if ($fails >= 5) {
                $_SESSION['qsyn_setup_lock_until'] = time() + 900;
            }
            return ['ok' => false, 'error' => 'invalid_setup_credentials'];
        }
        unset($_SESSION['qsyn_setup_failures'], $_SESSION['qsyn_setup_lock_until'], $_SESSION['qsyn_setup_csrf']);
        return ['ok' => true, 'configured' => true];
    }

    public static function csrf(): string
    {
        if (!isset($_SESSION['qsyn_setup_csrf'])) {
            $_SESSION['qsyn_setup_csrf'] = bin2hex(random_bytes(32));
        }
        return (string)$_SESSION['qsyn_setup_csrf'];
    }

    public static function validCsrf(string $token): bool
    {
        return strlen($token) === 64 &&
            isset($_SESSION['qsyn_setup_csrf']) &&
            hash_equals((string)$_SESSION['qsyn_setup_csrf'], $token);
    }
}
